---
title: "Project code"
author: "Jessica Hin (008515095)"
date: "2023-06-04"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup}
setwd('/Users/jessh/ADS503')
data <- read.csv('risk_factors_cervical_cancer.csv')

library(MASS)
library(dplyr)
library(caret)
library(ggplot2)
library(reshape2)
library(knitr)

colnames(data)[colnames(data) == "Smokes..years."] <- "Smokes.years."
colnames(data)[colnames(data) == "Smokes..packs.year." ] <- "Smokes.packs.year." 
colnames(data)[colnames(data) == "STDs..Time.since.last.diagnosis"] <- "STDs.Time.since.last.diagnosis"
colnames(data)[colnames(data) == "STDs..Number.of.diagnosis" ] <- "STDs.Number.of.diagnosis"
colnames(data)[colnames(data) == "STDs..Time.since.first.diagnosis"  ] <- "STDs.Time.since.first.diagnosis"  
colnames(data)[colnames(data) == "IUD..years."] <- "IUD.years."  
colnames(data)[colnames(data) == "Hormonal.Contraceptives..years." ] <- "Hormonal.Contraceptives.years." 


```

```{r splitting the data into 80/20 for Hinselmann}
hins_data <- data[,-c(34:36)]
set.seed(100)
hins_index <- createDataPartition(hins_data$Hinselmann, p = .80, list = FALSE)
hins_train <- hins_data[hins_index,]
hins_test <- hins_data[-hins_index,]
```

```{r preprocessing Hinselmann training set, warning = FALSE}
# checking for missing values
data_miss <- sapply(hins_train, function(x) sum(is.na(x)))

# changing all variables to integers
hins_train <- sapply(hins_train, as.integer)
hins_train <- as.data.frame(hins_train)

# need to make a function for mode
Mode <- function(x, na.rm = FALSE) {
  if(na.rm){
    x = x[!is.na(x)]
  }

  ux <- unique(x)
  return(ux[which.max(tabulate(match(x, ux)))])
}


# imputing the missing data
hins_train[,c(5,8,10, 12, 13:25,28:31)][is.na(hins_train[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(hins_train$STDs, na.rm = TRUE)

hins_train$Number.of.sexual.partners[is.na(hins_train$Number.of.sexual.partners)] <- round(mean(hins_train$Number.of.sexual.partners, na.rm = TRUE))

hins_train$First.sexual.intercourse[is.na(hins_train$First.sexual.intercourse)] <- round(mean(hins_train$First.sexual.intercourse, na.rm = TRUE))

hins_train$Num.of.pregnancies[is.na(hins_train$Num.of.pregnancies)] <- round(mean(hins_train$Num.of.pregnancies, na.rm = TRUE))

hins_train$Smokes.years.[is.na(hins_train$Smokes.years.)] <- round(mean(hins_train$Smokes.years., na.rm = TRUE))

hins_train$Smokes.packs.year.[is.na(hins_train$Smokes.packs.year.)] <- round(mean(hins_train$Smokes.packs.year., na.rm = TRUE))

hins_train$Hormonal.Contraceptives.years.[is.na(hins_train$Hormonal.Contraceptives.years.)] <- round(mean(hins_train$Hormonal.Contraceptives.years., na.rm = TRUE))

hins_train$IUD.years.[is.na(hins_train$IUD.years.)] <- round(mean(hins_train$IUD.years., na.rm = TRUE))

hins_train$STDs.Time.since.first.diagnosis[is.na(hins_train$STDs.Time.since.first.diagnosis)] <- Mode(hins_train$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(hins_train,as.factor) 
hins_train <- subset(hins_train, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))

# correlation plot
library(corrplot)
corrplot::corrplot(cor(hins_train))

# removing the predictors that were highly correlated
cor_idx <- findCorrelation(cor(hins_train), cutoff = .70)
hins_train <- hins_train[,-c(cor_idx)]

# plotting the correlation plot again
corrplot::corrplot(cor(hins_train))

# changing the boolean variables to factors
hins_train[,c(5,7,10:17,19:22)] <- lapply(hins_train[,c(5,7,10:17,19:22)], as.factor)
levels(hins_train$Hinselmann) = c("Negative", "Positive")

```


Using the equation $x = \frac{p(records)-rare}{1-p}$ where p is .20 to re balance the data set per response variable.

```{r rebalancing Hinselmann training set}
p = .20
records = as.integer(dim(hins_train)[1])
rare = table(hins_train$Hinselmann)[2]
resamp_times <- (p*records - rare)/(1-p)


pos_hins <- which(hins_train$Hinselmann == "Positive")
resamp <- sample(pos_hins, size = resamp_times, replace = TRUE)
resamp <- hins_train[resamp,]

rebal_hins_data <- rbind(hins_train,resamp)
table(rebal_hins_data$Hinselmann)[2]
table(rebal_hins_data$Hinselmann)[2]/dim(rebal_hins_data)[1]
```
```{r preprocessing for Hinselmann test data set, warning = FALSE}
# checking for missing values
data_miss <- sapply(hins_test, function(x) sum(is.na(x)))

# changing all variables to integers
hins_test<- sapply(hins_test, as.integer)
hins_test <- as.data.frame(hins_test)


# imputing the missing data
hins_test[,c(5,8,10, 12, 13:25,28:31)][is.na(hins_test[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(hins_test$STDs, na.rm = TRUE)

hins_test$Number.of.sexual.partners[is.na(hins_test$Number.of.sexual.partners)] <- round(mean(hins_test$Number.of.sexual.partners, na.rm = TRUE))

hins_test$First.sexual.intercourse[is.na(hins_test$First.sexual.intercourse)] <- round(mean(hins_test$First.sexual.intercourse, na.rm = TRUE))

hins_test$Num.of.pregnancies[is.na(hins_test$Num.of.pregnancies)] <- round(mean(hins_test$Num.of.pregnancies, na.rm = TRUE))

hins_test$Smokes.years.[is.na(hins_test$Smokes.years.)] <- round(mean(hins_test$Smokes.years., na.rm = TRUE))

hins_test$Smokes.packs.year.[is.na(hins_test$Smokes.packs.year.)] <- round(mean(hins_test$Smokes.packs.year., na.rm = TRUE))

hins_test$Hormonal.Contraceptives.years.[is.na(hins_test$Hormonal.Contraceptives.years.)] <- round(mean(hins_test$Hormonal.Contraceptives.years., na.rm = TRUE))

hins_test$IUD.years.[is.na(hins_test$IUD.years.)] <- round(mean(hins_test$IUD.years., na.rm = TRUE))

hins_test$STDs.Time.since.first.diagnosis[is.na(hins_test$STDs.Time.since.first.diagnosis)] <- Mode(hins_test$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(hins_test,as.factor) 
hins_test <- subset(hins_test, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))


# removing the predictors that were highly correlated from the training data set
hins_test <- hins_test[,-c(cor_idx)]

# changing the boolean variables to factors
hins_test[,c(5,7,10:17,19:22)] <- lapply(hins_test[,c(5,7,10:17,19:22)], as.factor)
levels(hins_test$Hinselmann) = c("Negative", "Positive")
```
```{r EDA for Hinselmann, warning=FALSE}

# Histograms of data
library(Hmisc)
hist.data.frame(hins_train[1:6], n.unique=1)
hist.data.frame(hins_train[7:12], n.unique=1)
hist.data.frame(hins_train[13:18], n.unique=1)
hist.data.frame(hins_train[19:22], n.unique=1)

```


```{r splitting data for Schiller}
schill_data <- data[,-c(33,35:36)]
set.seed(100)
schill_index <- createDataPartition(schill_data$Schiller, p = .80, list = FALSE)
schill_train <- schill_data[schill_index,]
schill_test <- schill_data[-schill_index,]
```


```{r preprocessing for Schiller training data set, warning = FALSE}
# checking for missing values
data_miss <- sapply(schill_train, function(x) sum(is.na(x)))

# changing all variables to integers
schill_train <- sapply(schill_train, as.integer)
schill_train <- as.data.frame(schill_train)

# imputing the missing data
schill_train[,c(5,8,10, 12, 13:25,28:31)][is.na(schill_train[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(schill_train$STDs, na.rm = TRUE)

schill_train$Number.of.sexual.partners[is.na(schill_train$Number.of.sexual.partners)] <- round(mean(schill_train$Number.of.sexual.partners, na.rm = TRUE))

schill_train$First.sexual.intercourse[is.na(schill_train$First.sexual.intercourse)] <- round(mean(schill_train$First.sexual.intercourse, na.rm = TRUE))

schill_train$Num.of.pregnancies[is.na(schill_train$Num.of.pregnancies)] <- round(mean(schill_train$Num.of.pregnancies, na.rm = TRUE))

schill_train$Smokes.years.[is.na(schill_train$Smokes.years.)] <- round(mean(schill_train$Smokes.years., na.rm = TRUE))

schill_train$Smokes.packs.year.[is.na(schill_train$Smokes.packs.year.)] <- round(mean(schill_train$Smokes.packs.year., na.rm = TRUE))

schill_train$Hormonal.Contraceptives.years.[is.na(schill_train$Hormonal.Contraceptives.years.)] <- round(mean(schill_train$Hormonal.Contraceptives.years., na.rm = TRUE))

schill_train$IUD.years.[is.na(schill_train$IUD.years.)] <- round(mean(schill_train$IUD.years., na.rm = TRUE))

schill_train$STDs.Time.since.first.diagnosis[is.na(schill_train$STDs.Time.since.first.diagnosis)] <- Mode(schill_train$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(schill_train,as.factor) 
schill_train <- subset(schill_train, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))

# correlation plot
corrplot::corrplot(cor(schill_train))

# removing the predictors that were highly correlated
cor_idx <- findCorrelation(cor(schill_train), cutoff = .70)
schill_train <- schill_train[,-c(cor_idx)]

# plotting the correlation plot again
corrplot::corrplot(cor(schill_train))

# changing the boolean variables to factors
schill_train[,c(5,7,10:17,19:22)] <- lapply(schill_train[,c(5,7,10:17,19:22)], as.factor)
levels(schill_train$Schiller) = c("Negative", "Positive")
```

```{r preprocessing schiller test data set, warning = FALSE}
# checking for missing values
data_miss <- sapply(schill_test, function(x) sum(is.na(x)))

# changing all variables to integers
schill_test<- sapply(schill_test, as.integer)
schill_test <- as.data.frame(schill_test)


# imputing the missing data
schill_test[,c(5,8,10, 12, 13:25,28:31)][is.na(schill_test[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(schill_test$STDs, na.rm = TRUE)

schill_test$Number.of.sexual.partners[is.na(schill_test$Number.of.sexual.partners)] <- round(mean(schill_test$Number.of.sexual.partners, na.rm = TRUE))

schill_test$First.sexual.intercourse[is.na(schill_test$First.sexual.intercourse)] <- round(mean(schill_test$First.sexual.intercourse, na.rm = TRUE))

schill_test$Num.of.pregnancies[is.na(schill_test$Num.of.pregnancies)] <- round(mean(schill_test$Num.of.pregnancies, na.rm = TRUE))

schill_test$Smokes.years.[is.na(schill_test$Smokes.years.)] <- round(mean(schill_test$Smokes.years., na.rm = TRUE))

schill_test$Smokes.packs.year.[is.na(schill_test$Smokes.packs.year.)] <- round(mean(schill_test$Smokes.packs.year., na.rm = TRUE))

schill_test$Hormonal.Contraceptives.years.[is.na(schill_test$Hormonal.Contraceptives.years.)] <- round(mean(schill_test$Hormonal.Contraceptives.years., na.rm = TRUE))

schill_test$IUD.years.[is.na(schill_test$IUD.years.)] <- round(mean(schill_test$IUD.years., na.rm = TRUE))

schill_test$STDs.Time.since.first.diagnosis[is.na(schill_test$STDs.Time.since.first.diagnosis)] <- Mode(schill_test$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(schill_test,as.factor) 
schill_test <- subset(schill_test, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))


# removing the predictors that were highly correlated from the training data set
schill_test <- schill_test[,-c(cor_idx)]

# changing the boolean variables to factors
schill_test[,c(5,7,10:17,19:22)] <- lapply(schill_test[,c(5,7,10:17,19:22)], as.factor)
levels(schill_test$Schiller) = c("Negative", "Positive")

```


```{r rebalancing Schiller training set}
p = .20
records = as.integer(dim(schill_train)[1])
rare = table(schill_train$Schiller)[2]
resamp_times <- (p*records - rare)/(1-p)


pos_schill <- which(schill_train$Schiller == "Positive")
resamp <- sample(pos_schill, size = resamp_times, replace = TRUE)
resamp <- schill_train[resamp,]

rebal_schill_data <- rbind(schill_train,resamp)
table(rebal_schill_data$Schiller)[2]
table(rebal_schill_data$Schiller)[2]/dim(rebal_schill_data)[1]

```



```{r splitting data for Citology}
cit_data <- data[,-c(33:34,36)]
set.seed(100)
cit_index <- createDataPartition(cit_data$Citology, p = .80, list = FALSE)
cit_train <- cit_data[cit_index,]
cit_test <- cit_data[-cit_index,]
```



```{r preprocessing citology training data set, warning = FALSE}
# checking for missing values
data_miss <- sapply(cit_train, function(x) sum(is.na(x)))

# changing all variables to integers
cit_train <- sapply(cit_train, as.integer)
cit_train <- as.data.frame(cit_train)

# need to make a function for mode
Mode <- function(x, na.rm = FALSE) {
  if(na.rm){
    x = x[!is.na(x)]
  }

  ux <- unique(x)
  return(ux[which.max(tabulate(match(x, ux)))])
}


# imputing the missing data
cit_train[,c(5,8,10, 12, 13:25,28:31)][is.na(cit_train[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(cit_train$STDs, na.rm = TRUE)

cit_train$Number.of.sexual.partners[is.na(cit_train$Number.of.sexual.partners)] <- round(mean(cit_train$Number.of.sexual.partners, na.rm = TRUE))

cit_train$First.sexual.intercourse[is.na(cit_train$First.sexual.intercourse)] <- round(mean(cit_train$First.sexual.intercourse, na.rm = TRUE))

cit_train$Num.of.pregnancies[is.na(cit_train$Num.of.pregnancies)] <- round(mean(cit_train$Num.of.pregnancies, na.rm = TRUE))

cit_train$Smokes.years.[is.na(cit_train$Smokes.years.)] <- round(mean(cit_train$Smokes.years., na.rm = TRUE))

cit_train$Smokes.packs.year.[is.na(cit_train$Smokes.packs.year.)] <- round(mean(cit_train$Smokes.packs.year., na.rm = TRUE))

cit_train$Hormonal.Contraceptives.years.[is.na(cit_train$Hormonal.Contraceptives.years.)] <- round(mean(cit_train$Hormonal.Contraceptives.years., na.rm = TRUE))

cit_train$IUD.years.[is.na(cit_train$IUD.years.)] <- round(mean(cit_train$IUD.years., na.rm = TRUE))

cit_train$STDs.Time.since.first.diagnosis[is.na(cit_train$STDs.Time.since.first.diagnosis)] <- Mode(cit_train$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(cit_train,as.factor) 
cit_train <- subset(cit_train, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))

# correlation plot
library(corrplot)
corrplot::corrplot(cor(cit_train))

# removing the predictors that were highly correlated
cor_idx <- findCorrelation(cor(cit_train), cutoff = .70)
cit_train <- cit_train[,-c(cor_idx)]

# plotting the correlation plot again
corrplot::corrplot(cor(cit_train))

# changing the boolean variables to factors
cit_train[,c(5,7,10:17,19:22)] <- lapply(cit_train[,c(5,7,10:17,19:22)], as.factor)
levels(cit_train$Citology) = c("Negative", "Positive")

```



```{r preprocessing for citology test set, warning = FALSE}

# checking for missing values
data_miss <- sapply(cit_test, function(x) sum(is.na(x)))

# changing all variables to integers
cit_test<- sapply(cit_test, as.integer)
cit_test <- as.data.frame(cit_test)


# imputing the missing data
cit_test[,c(5,8,10, 12, 13:25,28:31)][is.na(cit_test[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(cit_test$STDs, na.rm = TRUE)

cit_test$Number.of.sexual.partners[is.na(cit_test$Number.of.sexual.partners)] <- round(mean(cit_test$Number.of.sexual.partners, na.rm = TRUE))

cit_test$First.sexual.intercourse[is.na(cit_test$First.sexual.intercourse)] <- round(mean(cit_test$First.sexual.intercourse, na.rm = TRUE))

cit_test$Num.of.pregnancies[is.na(cit_test$Num.of.pregnancies)] <- round(mean(cit_test$Num.of.pregnancies, na.rm = TRUE))

cit_test$Smokes.years.[is.na(cit_test$Smokes.years.)] <- round(mean(cit_test$Smokes.years., na.rm = TRUE))

cit_test$Smokes.packs.year.[is.na(cit_test$Smokes.packs.year.)] <- round(mean(cit_test$Smokes.packs.year., na.rm = TRUE))

cit_test$Hormonal.Contraceptives.years.[is.na(cit_test$Hormonal.Contraceptives.years.)] <- round(mean(cit_test$Hormonal.Contraceptives.years., na.rm = TRUE))

cit_test$IUD.years.[is.na(cit_test$IUD.years.)] <- round(mean(cit_test$IUD.years., na.rm = TRUE))

cit_test$STDs.Time.since.first.diagnosis[is.na(cit_test$STDs.Time.since.first.diagnosis)] <- Mode(cit_test$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(cit_test,as.factor) 
cit_test <- subset(cit_test, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))


# removing the predictors that were highly correlated from the training data set
cit_test <- cit_test[,-c(cor_idx)]

# changing the boolean variables to factors
cit_test[,c(5,7,10:17,19:22)] <- lapply(cit_test[,c(5,7,10:17,19:22)], as.factor)
levels(cit_test$Citology) = c("Negative", "Positive")


```

```{r rebalacing Citology training set}
p = .20
records = as.integer(dim(cit_train)[1])
rare = table(cit_train$Citology)[2]
resamp_times <- (p*records - rare)/(1-p)


pos_cito <- which(cit_train$Citology == "Positive")
resamp <- sample(pos_cito, size = resamp_times, replace = TRUE)
resamp <- cit_train[resamp,]

rebal_cito_data <- rbind(cit_train,resamp)
table(rebal_cito_data$Citology)[2]
table(rebal_cito_data$Citology)[2]/dim(rebal_cito_data)[1]
```




```{r splitting the data into 80/20 for Biopsy}
bio_data <- data[,-c(33:35)]

set.seed(100)
bio_index <- createDataPartition(bio_data$Biopsy, p = .80, list = FALSE)
bio_train <- bio_data[hins_index,]
bio_test <- bio_data[-hins_index,]
```



```{r preproc for biopsy training data set, warning = FALSE}
# checking for missing values
data_miss <- sapply(bio_train, function(x) sum(is.na(x)))

# changing all variables to integers
bio_train <- sapply(bio_train, as.integer)
bio_train <- as.data.frame(bio_train)

# need to make a function for mode
Mode <- function(x, na.rm = FALSE) {
  if(na.rm){
    x = x[!is.na(x)]
  }

  ux <- unique(x)
  return(ux[which.max(tabulate(match(x, ux)))])
}


# imputing the missing data
bio_train[,c(5,8,10, 12, 13:25,28:31)][is.na(bio_train[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(bio_train$STDs, na.rm = TRUE)

bio_train$Number.of.sexual.partners[is.na(bio_train$Number.of.sexual.partners)] <- round(mean(bio_train$Number.of.sexual.partners, na.rm = TRUE))

bio_train$First.sexual.intercourse[is.na(bio_train$First.sexual.intercourse)] <- round(mean(bio_train$First.sexual.intercourse, na.rm = TRUE))

bio_train$Num.of.pregnancies[is.na(bio_train$Num.of.pregnancies)] <- round(mean(bio_train$Num.of.pregnancies, na.rm = TRUE))

bio_train$Smokes.years.[is.na(bio_train$Smokes.years.)] <- round(mean(bio_train$Smokes.years., na.rm = TRUE))

bio_train$Smokes.packs.year.[is.na(bio_train$Smokes.packs.year.)] <- round(mean(bio_train$Smokes.packs.year., na.rm = TRUE))

bio_train$Hormonal.Contraceptives.years.[is.na(bio_train$Hormonal.Contraceptives.years.)] <- round(mean(bio_train$Hormonal.Contraceptives.years., na.rm = TRUE))

bio_train$IUD.years.[is.na(bio_train$IUD.years.)] <- round(mean(bio_train$IUD.years., na.rm = TRUE))

bio_train$STDs.Time.since.first.diagnosis[is.na(bio_train$STDs.Time.since.first.diagnosis)] <- Mode(bio_train$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(bio_train,as.factor) 
bio_train <- subset(bio_train, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))

# correlation plot
library(corrplot)
corrplot::corrplot(cor(bio_train))

# removing the predictors that were highly correlated
cor_idx <- findCorrelation(cor(bio_train), cutoff = .70)
bio_train <- bio_train[,-c(cor_idx)]

# plotting the correlation plot again
corrplot::corrplot(cor(bio_train))

# changing the boolean variables to factors
bio_train[,c(5,7,10:17,19:22)] <- lapply(bio_train[,c(5,7,10:17,19:22)], as.factor)
levels(bio_train$Biopsy) = c("Negative", "Positive")

```


```{r preproc for biopsy test data set, warning = FALSE}
# checking for missing values
data_miss <- sapply(bio_test, function(x) sum(is.na(x)))

# changing all variables to integers
bio_test<- sapply(bio_test, as.integer)
bio_test <- as.data.frame(bio_test)


# imputing the missing data
bio_test[,c(5,8,10, 12, 13:25,28:31)][is.na(bio_test[,c(5,8,10, 12, 13:25,28:31)])] <- Mode(bio_test$STDs, na.rm = TRUE)

bio_test$Number.of.sexual.partners[is.na(bio_test$Number.of.sexual.partners)] <- round(mean(bio_test$Number.of.sexual.partners, na.rm = TRUE))

bio_test$First.sexual.intercourse[is.na(bio_test$First.sexual.intercourse)] <- round(mean(bio_test$First.sexual.intercourse, na.rm = TRUE))

bio_test$Num.of.pregnancies[is.na(bio_test$Num.of.pregnancies)] <- round(mean(bio_test$Num.of.pregnancies, na.rm = TRUE))

bio_test$Smokes.years.[is.na(bio_test$Smokes.years.)] <- round(mean(bio_test$Smokes.years., na.rm = TRUE))

bio_test$Smokes.packs.year.[is.na(bio_test$Smokes.packs.year.)] <- round(mean(bio_test$Smokes.packs.year., na.rm = TRUE))

bio_test$Hormonal.Contraceptives.years.[is.na(bio_test$Hormonal.Contraceptives.years.)] <- round(mean(bio_test$Hormonal.Contraceptives.years., na.rm = TRUE))

bio_test$IUD.years.[is.na(bio_test$IUD.years.)] <- round(mean(bio_test$IUD.years., na.rm = TRUE))

bio_test$STDs.Time.since.first.diagnosis[is.na(bio_test$STDs.Time.since.first.diagnosis)] <- Mode(bio_test$STDs.Time.since.first.diagnosis, na.rm = TRUE)

# remove certain variables because they only had 1 outcome, for the correlation plot
test <- lapply(bio_test,as.factor) 
bio_test <- subset(bio_test, select = -c(STDs.cervical.condylomatosis, STDs.pelvic.inflammatory.disease, STDs.AIDS))


# removing the predictors that were highly correlated from the training data set
bio_test <- bio_test[,-c(cor_idx)]

# changing the boolean variables to factors
bio_test[,c(5,7,10:17,19:22)] <- lapply(bio_test[,c(5,7,10:17,19:22)], as.factor)
levels(bio_test$Biopsy) = c("Negative", "Positive")

```

```{r rebalacing Biopsy training set}
p = .20
records = as.integer(dim(bio_train)[1])
rare = table(bio_train$Biopsy)[2]
resamp_times <- (p*records - rare)/(1-p)


pos_bio <- which(bio_train$Biopsy == "Positive"
                 )
resamp <- sample(pos_bio, size = resamp_times, replace = TRUE)
resamp <- bio_train[resamp,]

rebal_bio_data <- rbind(bio_train,resamp)
table(rebal_bio_data$Biopsy)[2]
table(rebal_bio_data$Biopsy)[2]/dim(rebal_bio_data)[1]
```



```{r Hinselmann Logistic Regression Model without weights, warning = FALSE}
set.seed(100)
ctrl <- trainControl(method = "cv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

hins_mod <- train(x = hins_train[,-22], y = hins_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(hins_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(hins_mod$finalModel$coefficients))

#predicting against the test set
hins_pred <- predict(hins_mod, hins_test[,-22])

# confusion matrix for the hins model
hins_cm<- confusionMatrix(hins_pred, hins_test[,22] )
hins_cm
kable(hins_cm$table)

# important variables for the model
hins_imp <- varImp(hins_mod, scale = FALSE)
plot(hins_imp)

# running the logistic regression model again with the top 5 important predictors
hins_top5 <- c("STDs.vulvo.perineal.condylomatosis", "Hormonal.Contraceptives", "Dx.HPV",
          "STDs.HIV", "Number.of.sexual.partners")

set.seed(100)
hins_new_mod <-train(x = hins_train[,hins_top5], y = hins_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(hins_new_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(hins_new_mod$finalModel$coefficients))

#predicting against the test set
hins_new_pred <- predict(hins_new_mod, hins_test[,-22])

# confusion matrix for the hins model
hins_new_cm<- confusionMatrix(hins_new_pred, hins_test[,22] )
hins_new_cm
kable(hins_new_cm$table)
```
```{r Hinselmann Model with Weights, warning = FALSE}

# creating weights for the imbalanced data set
model_weights <- ifelse(hins_train$Hinselmann == "Negative",
                        (1/table(hins_train$Hinselmann)[1]) * 0.5,
                        (1/table(hins_train$Hinselmann)[2]) * 0.5)

set.seed(100)
ctrl <- trainControl(method = "cv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

hins_mod_wt <- train(x = hins_train[,-22], y = hins_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)

#predicting against the test set
hins_pred <- predict(hins_mod_wt, hins_test[,-22])

# confusion matrix for the hins model
hins_cm<- confusionMatrix(hins_pred, hins_test[,22] )
hins_cm
kable(hins_cm$table)

# important variables for the model
hins_imp <- varImp(hins_mod_wt, scale = FALSE)
plot(hins_imp)

hins_top5 <- c("STDs.vulvo.perineal.condylomatosis", "Hormonal.Contraceptives", "STDs.Time.since.first.diagnosis",
          "STDs.HIV", "First.sexual.intercourse")

set.seed(100)
hins_new_mod <-train(x = hins_train[,hins_top5], y = hins_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)


#raw coefficients
data.frame(hins_new_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(hins_new_mod$finalModel$coefficients))

#predicting against the test set
hins_new_pred <- predict(hins_new_mod, hins_test[,-22])

# confusion matrix for the hins model
hins_new_cm<- confusionMatrix(hins_new_pred, hins_test[,22] )
hins_new_cm
kable(hins_new_cm$table)
```

```{r schiller logistic regression model, warning = FALSE}
set.seed(100)

ctrl <- trainControl(method = "cv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

schill_mod <- train(x = schill_train[,-22], y = schill_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(schill_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(schill_mod$finalModel$coefficients))

#predicting against the test set
schill_pred <- predict(schill_mod, schill_test[,-22])

# confusion matrix for the hins model
schill_cm<- confusionMatrix(schill_pred, schill_test[,22] )
schill_cm
kable(schill_cm$table)

# important variables for the model
schill_imp <- varImp(schill_mod, scale = FALSE)
plot(schill_imp)

# running the logistic regression model again with the top 5 important predictors
schill_top5 <- c("STDs.vulvo.perineal.condylomatosis", "Dx.HPV",
          "STDs.HIV", "Age", "Smokes")

set.seed(100)
schill_new_mod <-train(x = schill_train[,schill_top5], y = schill_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(schill_new_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(schill_new_mod$finalModel$coefficients))

#predicting against the test set
schill_new_pred <- predict(schill_new_mod, schill_test[,-22])

# confusion matrix for the hins model
schill_new_cm<- confusionMatrix(schill_new_pred, schill_test[,22] )
schill_new_cm
kable(schill_new_cm$table)
```
```{r shiller weight model, warning = FALSE}

model_weights <- ifelse(schill_train$Schiller == "Negative",
                        (1/table(schill_train$Schiller)[1]) * 0.5,
                        (1/table(schill_train$Schiller)[2]) * 0.5)

ctrl <- trainControl(method = "cv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

schill_mod_wt <- train(x = schill_train[,-22], y = schill_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)

#predicting against the test set
schill_pred <- predict(schill_mod_wt, schill_test[,-22])

# confusion matrix for the hins model
schill_cm<- confusionMatrix(schill_pred, schill_test[,22] )
schill_cm
kable(schill_cm$table)

# important variables for the model
schill_imp <- varImp(schill_mod_wt, scale = FALSE)
plot(schill_imp)

# running the logistic regression model again with the top 5 important predictors
schill_top5 <- c("STDs.vulvo.perineal.condylomatosis", "Hormonal.Contraceptives",
          "STDs.HIV", "Age", "First.sexual.intercourse")

set.seed(100)
schill_new_mod <-train(x = schill_train[,schill_top5], y = schill_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)

#predicting against the test set
schill_new_pred <- predict(schill_new_mod, schill_test[,-22])

# confusion matrix for the hins model
schill_new_cm<- confusionMatrix(schill_new_pred, schill_test[,22] )
schill_new_cm
kable(schill_new_cm$table)
```

```{r citology logistic regression, warning = FALSE}
set.seed(100)
cit_mod <- train(x = cit_train[,-22], y = cit_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(cit_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(cit_mod$finalModel$coefficients))

#predicting against the test set
cit_pred <- predict(cit_mod, cit_test[,-22])

# confusion matrix for the hins model
cit_cm<- confusionMatrix(cit_pred, cit_test[,22] )
cit_cm
kable(cit_cm$table)

# important variables for the model
cit_imp <- varImp(cit_mod, scale = FALSE)
plot(cit_imp)


# running the logistic regression model again with the top 5 important predictors
cit_top5 <- c("Hormonal.Contraceptives.years.", "STDs.HIV",
          "Dx", "STDs.vulvo.perineal.condylomatosis", "IUD.years.")

set.seed(100)
cit_new_mod <-train(x = cit_train[,cit_top5], y = cit_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(cit_new_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(cit_new_mod$finalModel$coefficients))

#predicting against the test set
cit_new_pred <- predict(cit_new_mod, cit_test[,-22])

# confusion matrix for the hins model
cit_new_cm<- confusionMatrix(cit_new_pred, cit_test[,22] )
cit_new_cm
kable(cit_new_cm$table)
```
```{r citology weighted model, warning = FALSE}
set.seed(100)
model_weights <- ifelse(cit_train$Citology == "Negative",
                        (1/table(cit_train$Citology)[1]) * 0.5,
                        (1/table(cit_train$Citology)[2]) * 0.5)
ctrl <- trainControl(method = "cv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE,
                     savePredictions = TRUE)

cit_mod_wt <- train(x = cit_train[,-22], y = cit_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)

#predicting against the test set
cit_pred <- predict(cit_mod_wt, schill_test[,-22])

# confusion matrix for the hins model
cit_cm<- confusionMatrix(cit_pred, cit_test[,22] )
cit_cm
kable(cit_cm$table)

# important variables for the model
cit_imp <- varImp(cit_mod_wt, scale = FALSE)
plot(cit_imp)

# running the logistic regression model again with the top 5 important predictors
cit_top5 <- c("Hormonal.Contraceptives.years.", "STDs.vulvo.perineal.condylomatosis",
          "STDs.HIV", "IUD.years.", "Dx")

set.seed(100)
cit_new_mod <-train(x = cit_train[,cit_top5], y = cit_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)

#predicting against the test set
cit_new_pred <- predict(cit_new_mod, cit_test[,-22])

# confusion matrix for the hins model
cit_new_cm<- confusionMatrix(cit_new_pred, cit_test[,22] )
cit_new_cm
kable(cit_new_cm$table)
```


```{r biopsy logistic regression model, warning = FALSE}
set.seed(100)
bio_mod <- train(x = bio_train[,-22], y = bio_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(bio_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(bio_mod$finalModel$coefficients))

#predicting against the test set
bio_pred <- predict(bio_mod, bio_test[,-22])

# confusion matrix for the hins model
bio_cm<- confusionMatrix(bio_pred, bio_test[,22] )
bio_cm
kable(bio_cm$table)

# important variables for the model
bio_imp <- varImp(bio_mod, scale = FALSE)
plot(bio_imp)

# running the logistic regression model again with the top 5 important predictors
bio_top5 <- c("STDs.vulvo.perineal.condylomatosis", "STDs.HIV",
          "Dx.HPV", "Dx.CIN", "Hormonal.Contraceptives.years.")

set.seed(100)
bio_new_mod <-train(x = bio_train[,bio_top5], y = bio_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl)

#raw coefficients
data.frame(bio_new_mod$finalModel$coefficients)

#odds ratios
data.frame(exp(bio_new_mod$finalModel$coefficients))

#predicting against the test set
bio_new_pred <- predict(bio_new_mod, bio_test[,-22])

# confusion matrix for the hins model
bio_new_cm<- confusionMatrix(bio_new_pred, bio_test[,22] )
bio_new_cm
kable(bio_new_cm$table)
```
```{r biopsy weighted model, warning = FALSE}
set.seed(100)

model_weights <- ifelse(bio_train$Biopsy == "Negative",
                        (1/table(bio_train$Biopsy)[1]) * 0.5,
                        (1/table(bio_train$Biopsy)[2]) * 0.5)

bio_mod_wt <- train(x = bio_train[,-22], y = bio_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)

#predicting against the test set
bio_pred <- predict(bio_mod_wt, bio_test[,-22])

# confusion matrix for the hins model
bio_cm<- confusionMatrix(bio_pred, bio_test[,22] )
bio_cm
kable(bio_cm$table)

# important variables for the model
bio_imp <- varImp(bio_mod, scale = FALSE)
plot(bio_imp)

# running the logistic regression model again with the top 5 important predictors
bio_top5 <- c("STDs.vulvo.perineal.condylomatosis", "STDs.HIV",
          "Dx.HPV", "Dx.CIN", "Hormonal.Contraceptives.years.")

set.seed(100)
bio_new_mod <-train(x = bio_train[,bio_top5], y = bio_train[,22],
               method = "glm",
               preProcess = c("center","scale"),
               trControl = ctrl,
               weights = model_weights)


#predicting against the test set
bio_new_pred <- predict(bio_new_mod, bio_test[,-22])

# confusion matrix for the hins model
bio_new_cm<- confusionMatrix(bio_new_pred, bio_test[,22] )
bio_new_cm
kable(bio_new_cm$table)
```


```{r totals for each target variable}
table(hins_test$Hinselmann)
table(schill_test$Schiller)
table(cit_test$Citology)
table(bio_test$Biopsy)
```



